/*
 In the QRTL model, two protons approach each other carrying their initial kinetic energy within their respective QRTL energy shells. When the proton shells collide, their kinetic energy is deposited into the lattice cells surrounding the impact point rather than remaining as a static energy blob. The localized energy excites the lattice, causing individual cells to behave as coupled mass–spring elements with displacement and velocity. As the collision energy is converted from kinetic energy into temporary potential energy, the up and down quark components of the two protons are driven toward the collision center, conceptually behaving like coupled springs. Their twist degrees of freedom simultaneously interact, producing competing attractive and repulsive effects. The attractive component temporarily concentrates and confines energy in the collision region, creating an unstable localized configuration whose energy has an effective mass-equivalent. The repulsive component provides the mechanism for the compressed configuration to release that stored energy.

 During this transient compression, the model proposes that borlagrino flow develops through the QRTL lattice as a consequence of the conversion and redistribution of kinetic energy into potential energy. The direction and circulation of this borlagrino flow provide the model's mechanism for generating an emergent electric-charge state. Charge is therefore treated as a dynamic property of the lattice flow rather than as a separate static energy shell. The amount of energy remains separately tracked from the borlagrino flow and charge so that the flow can redistribute or temporarily store energy without creating additional energy. As the attractive and repulsive interactions evolve, the borlagrino circulation changes and the charge signature can weaken or return toward equilibrium as the stored potential energy is released.

 At the same time, neighboring QRTL cells are coupled, so the localized collision disturbance does not remain confined to one cell. Energy and motion propagate through neighboring cells and can organize into a collective oscillatory pattern. The lattice therefore provides a mechanism for converting the initial localized collision into a measurable collective mode. A weighted collective lattice signal is constructed from the cell motion and energy, and its time evolution is analyzed using zero crossings and spectral analysis to determine its dominant frequency. The frequency is then converted into an energy using \(E=hf\), with the resulting energy expressed in GeV and compared with the approximately 125-GeV Higgs mass-energy scale.

 In this model, the Higgs-like state is therefore not created by simply assigning 125 GeV to a cell or by creating another proton-like QRTL energy shell. Instead, the proposed mechanism is that the collision produces a transient, localized, unstable collective excitation generated by quark compression, twist attraction and repulsion, borlagrino flow, and coupled lattice dynamics. If the measured collective mode produces an invariant energy near 125 GeV, together with the required coherence and spin-0-like behavior represented by the model, the state can be identified computationally as a Higgs-like resonance. The excitation then decays as the compressed energy is released through the lattice and the system returns toward energy symmetry.

 The complete proposed sequence is therefore: proton kinetic energy within QRTL shells → proton collision → localized energy deposition → kinetic-to-potential conversion → quark compression → twist attraction and repulsion → transient energy confinement → borlagrino flow → emergent charge state → coupled lattice propagation → collective oscillation → measured frequency → \(E=hf\) → approximately 125 GeV → transient Higgs-like state → energy release and decay → restoration toward equilibrium. This is the proposed QRTL mechanism and should be distinguished from the experimentally established Standard Model description of electric charge and Higgs-boson production.
 
 The QRTL lattice can be thought of as a calm ocean, with each lattice cell representing a small portion of the water. The proton collision is like throwing a stone into the ocean. When the stone hits, its kinetic energy is transferred into a small, localized area of the water. In the current process, the collision affected 93 of the 4,913 lattice cells, meaning the energy remained concentrated around the collision point rather than immediately spreading throughout the entire lattice. The collision gave these cells momentum and motion, creating the initial disturbance that will eventually propagate through the surrounding lattice.

 However, the current result shows that the affected cells are moving almost perfectly together. In the ocean analogy, this would be like the water around the stone all moving in nearly the same direction and at nearly the same phase. Because the waves are so closely synchronized, the calculated collective coherence is 1.0. As a result, the system currently treats essentially all of the lattice energy as belonging to the same collective resonant motion. The calculated lattice energy is about 1.078 × 10⁻⁶ joules, which corresponds to approximately 6.73 TeV when expressed as particle-energy equivalent.

 
 The Higgs boson has a measured mass of about 125.2 GeV, which corresponds through \(E=hf\) to an energy-equivalent frequency of approximately 3.03 × 10²⁵ Hz; in the QRTL analogy, this can be treated as a reference frequency for comparing the lattice's natural oscillation. However, a Higgs boson does not form simply because a system oscillates at 3.03 × 10²⁵ Hz, because Higgs production requires an appropriate particle interaction with sufficient center-of-mass energy and the relevant Standard Model couplings. Therefore, the QRTL model should determine its actual dominant frequency from the time evolution of the lattice after the collision, and then compare that measured natural/resonant frequency and its corresponding energy with the Higgs reference.

 The localized disturbance enters the **17³ quark lattice**, where QRTL dynamics evolve each cell's **displacement, velocity, and phase**. These responses are combined into a time-dependent **collective signal** using displacement and velocity projected along the collision direction, rather than maximum local energy.

 The `collectiveSignal(t)` is analyzed by **FFT** to identify the dominant **resonant frequency**. The lattice response at that frequency is then analyzed to determine each cell's **amplitude and phase**, producing the **spatial resonant mode**. The mode amplitude is used to calculate `resonantModeEnergy`, representing the energy contained in the collective mode rather than the energy of the single most energetic cell.

 Finally, `resonantModeEnergy` is compared with the **125 GeV Higgs reference energy** (~`2.0027e-8 J`) to determine whether the naturally generated mode falls within the specified tolerance.

 **In short:**
 **Localized collision → lattice evolution → collective signal → FFT → resonant frequency → spatial mode → mode energy → 125 GeV comparison → Higgs-like mode test.**

 */
import SwiftUI
import SceneKit
import simd
import Combine

// ============================================================
// MARK: - CONTENT VIEW
// ============================================================

struct ContentView: View {

    @StateObject private var simulation = QRTLSimulation()

    var body: some View {

        ZStack(alignment: .top) {

            Color.black
                .ignoresSafeArea()

            VStack(spacing: 0) {

                // ========================================================
                // 3D SCENE
                // ========================================================

                SceneView(
                    scene: simulation.scene,
                    pointOfView: simulation.cameraNode,
                    options: [
                        .allowsCameraControl,
                        .autoenablesDefaultLighting
                    ]
                )
                .frame(maxWidth: .infinity)
                .frame(height: 470)

                // ========================================================
                // PHYSICS INFORMATION
                // ========================================================

                ScrollView {

                    VStack(spacing: 10) {

                        collisionCard
                        shellEnergyCard
                        resonanceCard

                        Button("Reset Simulation") {
                            simulation.reset()
                        }
                        .buttonStyle(.borderedProminent)
                        .padding(.vertical, 8)
                    }
                    .padding()
                }
                .background(Color.black)
            }
        }
        .onAppear {
            simulation.start()
        }
        .onDisappear {
            simulation.stop()
        }
    }

    // ========================================================
    // MARK: - COLLISION CARD
    // ========================================================

    private var collisionCard: some View {

        monitorCard(
            title: "COLLISION",
            symbol: "bolt.fill"
        ) {

            HStack {

                valueRow(
                    label: "Proton A",
                    value: simulation.protonAState
                )

                Spacer()

                valueRow(
                    label: "Distance",
                    value: String(
                        format: "%.3f",
                        simulation.protonDistance
                    )
                )

                Spacer()

                valueRow(
                    label: "Proton B",
                    value: simulation.protonBState
                )
            }

            Divider()
                .background(Color.gray)

            metricRow(
                label: "Collision Energy",
                value: "\(formatScientific(simulation.collisionKineticEnergyJ)) J"
            )

            metricRow(
                label: "Collision Energy",
                value: "\(formatGeV(simulation.collisionKineticEnergyJ)) GeV"
            )

            Divider()
                .background(Color.gray)

            statusRow(
                label: "Collision",
                status: simulation.collisionOccurred
                    ? "OCCURRED"
                    : "APPROACHING",
                active: simulation.collisionOccurred
            )
        }
    }

    // ========================================================
    // MARK: - QRTL SHELL ENERGY CARD
    // ========================================================

    private var shellEnergyCard: some View {

        monitorCard(
            title: "QRTL SHELL ENERGY",
            symbol: "circle.hexagongrid.fill"
        ) {

            // Primary shell-energy indicator

            Text(
                "\(formatGeV(simulation.energyState.shellEnergy)) GeV"
            )
            .font(
                .system(
                    size: 30,
                    weight: .bold,
                    design: .monospaced
                )
            )
            .foregroundColor(.cyan)
            .frame(maxWidth: .infinity)

            Text("Shell Energy")
                .font(.caption)
                .foregroundColor(.gray)
                .frame(maxWidth: .infinity)

            Divider()
                .background(Color.gray)

            metricRow(
                label: "Shell Energy",
                value: "\(formatScientific(simulation.energyState.shellEnergy)) J"
            )

            metricRow(
                label: "Equilibrium Energy",
                value: "\(formatScientific(simulation.energyState.equilibriumShellEnergy)) J"
            )

            metricRow(
                label: "Deformation",
                value: format(simulation.energyState.deformation)
            )

            metricRow(
                label: "Instability",
                value: formatPercent(simulation.energyState.shellInstability)
            )

            Divider()
                .background(Color.gray)

            statusRow(
                label: "Shell State",
                status: simulation.energyState.isUnstable
                    ? "UNSTABLE"
                    : "STABLE",
                active: simulation.energyState.isUnstable
            )
        }
    }

    // ========================================================
    // MARK: - RESONANT MODE CARD
    // ========================================================

    private var resonanceCard: some View {

        monitorCard(
            title: "RESONANT MODE",
            symbol: "waveform.path.ecg"
        ) {

            // Primary resonant mass-energy indicator

            Text(
                "\(formatGeV(simulation.resonantModeEnergy)) GeV"
            )
            .font(
                .system(
                    size: 30,
                    weight: .bold,
                    design: .monospaced
                )
            )
            .foregroundColor(.purple)
            .frame(maxWidth: .infinity)

            Text("Resonant Mass-Energy")
                .font(.caption)
                .foregroundColor(.gray)
                .frame(maxWidth: .infinity)

            Divider()
                .background(Color.gray)

            metricRow(
                label: "Mode Energy",
                value: "\(formatScientific(simulation.resonantModeEnergy)) J"
            )

            metricRow(
                label: "Target",
                value: "125.000 GeV"
            )

            metricRow(
                label: "Distance From Target",
                value: "\(format(simulation.resonantMassGeV - QRTLConstants.targetHiggsMassGeV)) GeV"
            )

            Divider()
                .background(Color.gray)

            metricRow(
                label: "Frequency",
                value: "\(formatScientific(simulation.resonantFrequencyHz)) Hz"
            )

            metricRow(
                label: "Coherence",
                value: formatPercent(simulation.higgsMode.coherence)
            )

            statusRow(
                label: "Mode",
                status: simulation.higgsModeStatus,
                active: simulation.higgsMode.active
            )
        }
    }

    // ========================================================
    // MARK: - CARD HELPER
    // ========================================================

    private func monitorCard<Content: View>(
        title: String,
        symbol: String,
        @ViewBuilder content: () -> Content
    ) -> some View {

        VStack(
            alignment: .leading,
            spacing: 10
        ) {

            HStack {

                Image(systemName: symbol)

                Text(title)
                    .font(.headline)
                    .fontWeight(.bold)

                Spacer()
            }
            .foregroundColor(.white)

            content()
        }
        .padding()
        .background(
            RoundedRectangle(cornerRadius: 12)
                .fill(Color.white.opacity(0.08))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 12)
                .stroke(
                    Color.white.opacity(0.15),
                    lineWidth: 1
                )
        )
    }

    // ========================================================
    // MARK: - ROW HELPERS
    // ========================================================

    private func metricRow(
        label: String,
        value: String
    ) -> some View {

        HStack {

            Text(label)
                .foregroundColor(.gray)

            Spacer()

            Text(value)
                .foregroundColor(.white)
                .monospacedDigit()
        }
        .font(.system(size: 14))
    }

    private func valueRow(
        label: String,
        value: String
    ) -> some View {

        VStack(spacing: 3) {

            Text(label)
                .font(.caption)
                .foregroundColor(.gray)

            Text(value)
                .font(.system(size: 13))
                .foregroundColor(.white)
        }
    }

    private func statusRow(
        label: String,
        status: String,
        active: Bool
    ) -> some View {

        HStack {

            Text(label)
                .foregroundColor(.gray)

            Spacer()

            Text(status)
                .fontWeight(.semibold)
                .foregroundColor(
                    active ? .green : .orange
                )
        }
    }

    // ========================================================
    // MARK: - FORMATTERS
    // ========================================================

    private func format(
        _ value: Double
    ) -> String {

        guard value.isFinite else {
            return "—"
        }

        return String(
            format: "%.6f",
            value
        )
    }

    private func formatGeV(
        _ energyJ: Double
    ) -> String {

        guard energyJ.isFinite else {
            return "—"
        }

        return String(
            format: "%.6f",
            energyJ / QRTLConstants.joulesPerGeV
        )
    }

    private func formatPercent(
        _ value: Double
    ) -> String {

        guard value.isFinite else {
            return "—"
        }

        return String(
            format: "%.1f%%",
            value * 100.0
        )
    }

    private func formatScientific(
        _ value: Double
    ) -> String {

        guard value.isFinite else {
            return "—"
        }

        return String(
            format: "%.3e",
            value
        )
    }
}
