/*
 In the QRTL model, two protons approach each other carrying their initial kinetic energy within their respective QRTL energy shells. When the proton shells collide, their kinetic energy is deposited into the lattice cells surrounding the impact point rather than remaining as a static energy blob. The localized energy excites the lattice, causing individual cells to behave as coupled mass–spring elements with displacement and velocity. As the collision energy is converted from kinetic energy into temporary potential energy, the up and down quark components of the two protons are driven toward the collision center, conceptually behaving like coupled springs. Their twist degrees of freedom simultaneously interact, producing competing attractive and repulsive effects. The attractive component temporarily concentrates and confines energy in the collision region, creating an unstable localized configuration whose energy has an effective mass-equivalent. The repulsive component provides the mechanism for the compressed configuration to release that stored energy.

 During this transient compression, the model proposes that borlagrino flow develops through the QRTL lattice as a consequence of the conversion and redistribution of kinetic energy into potential energy. The direction and circulation of this borlagrino flow provide the model's mechanism for generating an emergent electric-charge state. Charge is therefore treated as a dynamic property of the lattice flow rather than as a separate static energy shell. The amount of energy remains separately tracked from the borlagrino flow and charge so that the flow can redistribute or temporarily store energy without creating additional energy. As the attractive and repulsive interactions evolve, the borlagrino circulation changes and the charge signature can weaken or return toward equilibrium as the stored potential energy is released.

 At the same time, neighboring QRTL cells are coupled, so the localized collision disturbance does not remain confined to one cell. Energy and motion propagate through neighboring cells and can organize into a collective oscillatory pattern. The lattice therefore provides a mechanism for converting the initial localized collision into a measurable collective mode. A weighted collective lattice signal is constructed from the cell motion and energy, and its time evolution is analyzed using zero crossings and spectral analysis to determine its dominant frequency. The frequency is then converted into an energy using \(E=hf\), with the resulting energy expressed in GeV and compared with the approximately 125-GeV Higgs mass-energy scale.

 In this model, the Higgs-like state is therefore not created by simply assigning 125 GeV to a cell or by creating another proton-like QRTL energy shell. Instead, the proposed mechanism is that the collision produces a transient, localized, unstable collective excitation generated by quark compression, twist attraction and repulsion, borlagrino flow, and coupled lattice dynamics. If the measured collective mode produces an invariant energy near 125 GeV, together with the required coherence and spin-0-like behavior represented by the model, the state can be identified computationally as a Higgs-like resonance. The excitation then decays as the compressed energy is released through the lattice and the system returns toward energy symmetry.

 The complete proposed sequence is therefore: proton kinetic energy within QRTL shells → proton collision → localized energy deposition → kinetic-to-potential conversion → quark compression → twist attraction and repulsion → transient energy confinement → borlagrino flow → emergent charge state → coupled lattice propagation → collective oscillation → measured frequency → \(E=hf\) → approximately 125 GeV → transient Higgs-like state → energy release and decay → restoration toward equilibrium. This is the proposed QRTL mechanism and should be distinguished from the experimentally established Standard Model description of electric charge and Higgs-boson production.
 
 The QRTL lattice can be thought of as a calm ocean, with each lattice cell representing a small portion of the water. The proton collision is like throwing a stone into the ocean. When the stone hits, its kinetic energy is transferred into a small, localized area of the water. In the current process, the collision affected 93 of the 4,913 lattice cells, meaning the energy remained concentrated around the collision point rather than immediately spreading throughout the entire lattice. The collision gave these cells momentum and motion, creating the initial disturbance that will eventually propagate through the surrounding lattice.

 However, the current result shows that the affected cells are moving almost perfectly together. In the ocean analogy, this would be like the water around the stone all moving in nearly the same direction and at nearly the same phase. Because the waves are so closely synchronized, the calculated collective coherence is 1.0. As a result, the system currently treats essentially all of the lattice energy as belonging to the same collective resonant motion. The calculated lattice energy is about 1.078 × 10⁻⁶ joules, which corresponds to approximately 6.73 TeV when expressed as particle-energy equivalent.

 


 */
import SwiftUI

import SceneKit

import simd

import Combine

// ============================================================

// MARK: - CONTENT VIEW

// ============================================================

struct ContentView: View {

    @StateObject private var simulation = QRTLSimulation()

    var body: some View {

        ZStack(alignment: .top) {

            Color.black

                .ignoresSafeArea()

            VStack(spacing: 0) {

                SceneView(

                    scene: simulation.scene,

                    pointOfView: simulation.cameraNode,

                    options: [

                        .allowsCameraControl,

                        .autoenablesDefaultLighting

                    ]

                )

                .frame(maxWidth: .infinity)

                .frame(height: 470)

                ScrollView {

                    VStack(spacing: 10) {

                        collisionCard

                        qrtlShellCard

                        latticeCard

                        energyCard

                        higgsCard

                        Button("Reset Simulation") {

                            simulation.reset()

                        }

                        .buttonStyle(.borderedProminent)

                        .padding(.vertical, 8)

                    }

                    .padding()

                }

                .background(Color.black)

            }

        }

        .onAppear {

            simulation.start()

        }

        .onDisappear {

            simulation.stop()

        }

    }

    // ========================================================

    // MARK: - COLLISION CARD

    // ========================================================

    private var collisionCard: some View {

        monitorCard(

            title: "COLLISION",

            symbol: "bolt.fill"

        ) {

            HStack {

                valueRow(

                    label: "Proton A",

                    value: simulation.protonAState

                )

                Spacer()

                valueRow(

                    label: "Distance",

                    value: String(

                        format: "%.3f",

                        simulation.protonDistance

                    )

                )

                Spacer()

                valueRow(

                    label: "Proton B",

                    value: simulation.protonBState

                )

            }

            Divider()

                .background(Color.gray)

            statusRow(

                label: "Collision",

                status: simulation.collisionOccurred

                    ? "OCCURRED"

                    : "APPROACHING",

                active: simulation.collisionOccurred

            )

        }

    }

    // ========================================================

    // MARK: - QRTL SHELL CARD

    // ========================================================

    private var qrtlShellCard: some View {

        monitorCard(

            title: "QRTL SHELL",

            symbol: "circle.hexagongrid.fill"

        ) {

            metricRow(

                label: "Shell Energy",

                value: "\(format(simulation.energyState.shellEnergy))"

            )

            metricRow(

                label: "Equilibrium Energy",

                value: "\(format(simulation.energyState.equilibriumShellEnergy))"

            )

            metricRow(

                label: "Instability",

                value: "\(formatPercent(simulation.energyState.shellInstability))"

            )

            metricRow(

                label: "Deformation",

                value: "\(format(simulation.energyState.deformation))"

            )
            metricRow(label: "Borlagrino |flow|", value: format(simulation.averageBorlagrinoMagnitude))
            metricRow(label: "Net Emergent Charge", value: format(simulation.netEmergentCharge))
            metricRow(label: "Charge Asymmetry", value: formatPercent(simulation.chargeAsymmetry))
            Divider()

                .background(Color.gray)

            statusRow(

                label: "Shell State",

                status: simulation.energyState.isUnstable

                    ? "UNSTABLE"

                    : "STABLE",

                active: simulation.energyState.isUnstable

            )

        }

    }

    // ========================================================

    // MARK: - LATTICE CARD

    // ========================================================

    private var latticeCard: some View {

        monitorCard(

            title: "QUARK-LATTICE CA",

            symbol: "square.grid.3x3.fill"

        ) {

            metricRow(

                label: "Active Cells",

                value: "\(simulation.activeCellCount)"

            )

            metricRow(

                label: "Collective Coherence",

                value: formatPercent(simulation.collectiveCoherence)

            )

            metricRow(

                label: "Average Strain",

                value: format(simulation.averageStrain)

            )

            metricRow(

                label: "Average Twist",

                value: format(simulation.averageTwist)

            )

            metricRow(

                label: "Collective Amplitude",

                value: format(simulation.collectiveAmplitude)

            )

            Divider()

                .background(Color.gray)

            statusRow(

                label: "Lattice State",

                status: simulation.latticeExcited

                    ? "EXCITED"

                    : "EQUILIBRIUM",

                active: simulation.latticeExcited

            )

        }

    }

    // ========================================================

    // MARK: - ENERGY CARD

    // ========================================================

    private var energyCard: some View {

        monitorCard(

            title: "ENERGY",

            symbol: "waveform.path.ecg"

        ) {

            metricRow(

                label: "Formation Threshold",

                value: "\(format(simulation.formationThresholdEnergy))"

            )

            metricRow(

                label: "Lattice Energy",

                value: "\(format(simulation.latticeEnergy))"

            )

            metricRow(

                label: "Resonant Mode Energy",

                value: "\(format(simulation.resonantModeEnergy))"

            )

            metricRow(

                label: "Energy Concentration",

                value: formatPercent(simulation.energyConcentration)

            )

        }

    }

    // ========================================================

    // MARK: - HIGGS-LIKE MODE CARD

    // ========================================================

    private var higgsCard: some View {

        monitorCard(

            title: "HIGGS-LIKE MODE",

            symbol: "wave.3.right"

        ) {

            metricRow(

                label: "Resonant Mass",

                value: "\(format(simulation.resonantMassGeV)) GeV"

            )

            metricRow(

                label: "Formation Threshold",

                value: "\(format(simulation.formationThresholdEnergy))"

            )

            metricRow(

                label: "Mode Energy",

                value: "\(format(simulation.resonantModeEnergy))"

            )

            metricRow(

                label: "Frequency",

                value: "\(formatScientific(simulation.resonantFrequencyHz)) Hz"

            )

            metricRow(

                label: "Angular Frequency",

                value: "\(formatScientific(simulation.resonantAngularFrequency)) rad/s"

            )

            metricRow(

                label: "Wavelength",

                value: "\(formatScientific(simulation.resonantWavelengthMeters)) m"

            )

            metricRow(

                label: "FFT Samples",

                value: "\(simulation.spectralSampleCount) / \(QRTLConstants.spectralSampleCount)"

            )

            metricRow(

                label: "Nyquist Limit",

                value: "\(formatScientific(simulation.spectralNyquistHz)) Hz"

            )

            metricRow(

                label: "Amplitude",

                value: format(simulation.higgsMode.amplitude)

            )

            metricRow(

                label: "Coherence",

                value: formatPercent(simulation.higgsMode.coherence)

            )

            Divider()

                .background(Color.gray)

            metricRow(

                label: "Target",

                value: "125.000 GeV"

            )

            metricRow(

                label: "Target Frequency",

                value: "\(formatScientific(simulation.targetFrequencyHz)) Hz"

            )

            metricRow(

                label: "Distance",

                value: "\(format(simulation.massDistanceFromTarget)) GeV"

            )

            Divider()

                .background(Color.gray)

            statusRow(

                label: "Mode",

                status: simulation.higgsModeStatus,

                active: simulation.higgsMode.active

            )

        }

    }

    // ========================================================

    // MARK: - CARD HELPERS

    // ========================================================

    private func monitorCard<Content: View>(

        title: String,

        symbol: String,

        @ViewBuilder content: () -> Content

    ) -> some View {

        VStack(

            alignment: .leading,

            spacing: 10

        ) {

            HStack {

                Image(systemName: symbol)

                Text(title)

                    .font(.headline)

                Spacer()

            }

            .foregroundColor(.white)

            content()

        }

        .padding()

        .background(

            RoundedRectangle(cornerRadius: 12)

                .fill(Color.white.opacity(0.08))

        )

        .overlay(

            RoundedRectangle(cornerRadius: 12)

                .stroke(

                    Color.white.opacity(0.15),

                    lineWidth: 1

                )

        )

    }

    private func metricRow(

        label: String,

        value: String

    ) -> some View {

        HStack {

            Text(label)

                .foregroundColor(.gray)

            Spacer()

            Text(value)

                .foregroundColor(.white)

                .monospacedDigit()

        }

        .font(.system(size: 14))

    }

    private func valueRow(

        label: String,

        value: String

    ) -> some View {

        VStack(spacing: 3) {

            Text(label)

                .font(.caption)

                .foregroundColor(.gray)

            Text(value)

                .font(.system(size: 13))

                .foregroundColor(.white)

        }

    }

    private func statusRow(

        label: String,

        status: String,

        active: Bool

    ) -> some View {

        HStack {

            Text(label)

                .foregroundColor(.gray)

            Spacer()

            Text(status)

                .fontWeight(.semibold)

                .foregroundColor(

                    active ? .green : .orange

                )

        }

    }

    private func format(

        _ value: Double

    ) -> String {

        String(

            format: "%.6f",

            value

        )

    }

    private func formatPercent(

        _ value: Double

    ) -> String {

        String(

            format: "%.1f%%",

            value * 100.0

        )

    }

    private func formatScientific(

        _ value: Double

    ) -> String {

        guard value.isFinite,

              value > 0

        else {

            return "0"

        }

        return String(

            format: "%.3e",

            value

        )

    }

}




